# Render Blueprint for Farmer's Radio App
services:
  - type: web
    name: farmers-radio-app
    env: python
    buildCommand: "./build.sh"
    startCommand: "daphne radio_project.asgi:application -p $PORT -b 0.0.0.0"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "farmers-radio-app.onrender.com,*.onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: farmers-radio-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: farmers-radio-redis
          property: connectionString

  - type: pserv
    name: farmers-radio-db
    databaseName: farmers_radio
    databaseUser: farmers_radio_user

  - type: redis
    name: farmers-radio-redis
    ipAllowList: []