# Render Blueprint for Bellefu Radio App
services:
  - type: web
    name: bellefu-radio-app
    env: python
    buildCommand: "./build.sh"
    startCommand: "daphne radio_project.asgi:application -p $PORT -b 0.0.0.0"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "bellefu-radio-app.onrender.com,*.onrender.com"
      - key: DJANGO_SETTINGS_MODULE
        value: "radio_project.settings"
      - key: DJANGO_SUPERUSER_USERNAME
        value: "admin"
      - key: DJANGO_SUPERUSER_EMAIL
        value: "admin@bellefuradio.com"
      - key: DJANGO_SUPERUSER_PASSWORD
        value: "admin123"
      - key: DATABASE_URL
        fromDatabase:
          name: bellefu-radio-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: bellefu-radio-redis
          property: connectionString

  - type: redis
    name: bellefu-radio-redis
    ipAllowList: []

databases:
  - name: bellefu-radio-db
    databaseName: bellefu_radio
    user: bellefu_radio_user